[package]
name = "tetris_defense"
version = "0.1.0"
edition = "2021"

[dependencies]
avian2d = { git = "https://github.com/Jondolf/avian", branch = "main" }
bevy = { git = "https://github.com/bevyengine/bevy", branch = "release-0.15.0" }
